### ISSUE TITLE
Spreadsheet::XLSX column limitation

### ISSUE THREAD

**Issue by denbyangus** [do-/eludia#24]
Hi there

We use your modules all the time in custom scripts for our clients.
I have recently encountered a workbook with sheets containing more than 702 columns (i.e.beyond column ZZ).
I have located the issue in your module and made a local hack but obviously I'd prefer that the source be updated so everyone can benefit.

The change requires the replacement of

      if (/^\<c r=\"([A-Z])([A-Z]?)(\d+)\"/) {

        $col = ord ($1) - 65;

        if ($2) {
          $col++;
          $col *= 26;
          $col += (ord ($2) - 65);
        }

with

      if (/^\<c r=\"([A-Z])([A-Z]*)(\d+)\"/) {

        $col = ord ($1) - 65;

        my $rest = $2;
        while (my $c = substr($rest, 0, 1, '')) {
          $col++;
          $col *= 26;
          $col += (ord ($c) - 65);
        }

Thanks
Denby

**Comment by jonny64** [comment]
Denby,
Where this code comes from? Is it related to new XLSX skin? I can't find this code in eludia
Could you please prepare merge request for eludia?

**Comment by moominpappa** [comment]
Это вроде другой модуль? spreadsheet::xlsx13:32, 13 декабря 2016 г., Maksim Gruzdev <notifications@github.com>:Denby,
Where this code comes from? Is it related to new XLSX skin? I can't find this code in eludia
Could you please prepare merge request for eludia?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by do-** [comment]
Sorry denbyangus, I've abandoned Spreadsheet::XLSX 8 years ago, and here is not the place to post related fixes. If http://search.cpan.org/~mikeb/ don't answer, the project is well and sure dead. But please feel free to fork the codebase and start yous one.
